# All rules here : https://realm.github.io/SwiftLint/rule-directory.html
 
analyzer_rules:
  - capture_variable
  - typesafe_array_init
  - unused_declaration
  - unused_import
 
excluded:
  - scripts/
  - fastlane/
  - vendor/
 
file_name:
  excluded:
    - Localizations.generated.swift
 
identifier_name:
  min_length:
    - 2
  max_length:
    - 50
  excluded:
    - x
    - y
 
type_name:
  min_length: 3
  max_length: 60
  excluded:
    - T
 
line_length:
  warning: 150
 
opt_in_rules:
  # Default rules :
  - block_based_kvo
  - class_delegate_protocol
  - closing_brace
  - closure_parameter_position
  - colon
  - comma
  - comment_spacing
  - compiler_protocol_init
  - computed_accessors_order
  - control_statement
  - custom_rules
  - cyclomatic_complexity
  - deployment_target
  - discouraged_direct_init
  - duplicate_enum_cases
  - duplicate_imports
  - duplicated_key_in_dictionary_literal
  - dynamic_inline
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - file_length
  - for_where
  - force_cast
  - force_try
  - function_body_length
  - function_parameter_count
  - generic_type_name
  - identifier_name
  - implicit_getter
  - inclusive_language
  - inert_defer
  - is_disjoint
  - large_tuple
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_hashing
  - legacy_nsgeometry_functions
  - legacy_random
  - line_length
  - mark
  - multiple_closures_with_trailing_closure
  - nesting
  - no_fallthrough_only
  - no_space_in_method_call
  - notification_center_detachment
  - ns_number_init_as_function_reference
  - nsobject_prefer_isequal
  - opening_brace
  - operator_whitespace
  - orphaned_doc_comment
  - private_over_fileprivate
  - private_unit_test
  - protocol_property_accessors_order
  - reduce_boolean
  - redundant_discardable_let
  - redundant_objc_attribute
  - redundant_optional_initialization
  - redundant_set_access_control
  - redundant_string_enum_value
  - redundant_void_return
  - return_arrow_whitespace
  - self_in_property_initialization
  - shorthand_operator
  - statement_position
  - superfluous_disable_command
  - switch_case_alignment
  - syntactic_sugar
  - todo
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - type_body_length
  - type_name
  - unavailable_condition
  - unneeded_break_in_switch
  - unused_capture_list
  - unused_closure_parameter
  - unused_control_flow_label
  - unused_enumerated
  - unused_optional_binding
  - unused_setter_value
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_whitespace
  - void_function_in_ternary
  - void_return
  - xctfail_message
 
  # Opt-in rules :
  # - accessibility_label_for_image
  - accessibility_trait_for_button
  - anonymous_argument_in_multiline_closure
  # - anyobject_protocol => deprecated
  - array_init
  - attributes
  # - balanced_xctest_lifecycle
  - closure_body_length
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - comma_inheritance
  # - conditional_returns_on_newline
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - contains_over_range_nil_comparison
  - convenience_type
  - discarded_notification_center_observer
  - discouraged_assert
  - discouraged_none_name
  - discouraged_object_literal
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - empty_collection_literal
  - empty_count
  - empty_string
  - empty_xctest_method
  - enum_case_associated_values_count
  # - expiring_todo
  # - explicit_acl
  # - explicit_enum_raw_value
  - explicit_init
  # - explicit_self
  # - explicit_top_level_acl
  # - explicit_type_interface
  # - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - file_header
  - file_name
  - file_name_no_space
  - file_types_order
  - first_where
  - flatmap_over_map_reduce
  - force_unwrapping
  - function_default_parameter_at_end
  - ibinspectable_in_extension
  - implicit_return
  - implicitly_unwrapped_optional
  - indentation_width
  - joined_default_parameter
  - last_where
  - legacy_multiple
  - legacy_objc_type
  - let_var_whitespace
  - literal_expression_end_indentation
  # - local_doc_comment
  - lower_acl_than_parent
  # - missing_docs
  - modifier_order
  - multiline_arguments
  - multiline_arguments_brackets
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets 
  - nimble_operator
  - no_extension_access_modifier
  - no_grouping_extension
  - no_magic_numbers
  - nslocalizedstring_key
  - nslocalizedstring_require_bundle
  - number_separator
  # - object_literal
  - operator_usage_whitespace
  - optional_enum_case_matching
  - overridden_super_call
  - override_in_extension
  - pattern_matching_keywords
  # - prefer_nimble
  - prefer_self_in_static_references
  - prefer_self_type_over_type_of_self
  - prefer_zero_over_explicit_init
  - prefixed_toplevel_constant
  - private_action
  - private_outlet
  # - private_subject
  - prohibited_interface_builder
  - prohibited_super_call
  - quick_discouraged_call
  - quick_discouraged_focused_test
  - quick_discouraged_pending_test
  # - raw_value_for_camel_cased_codable_enum
  - reduce_into
  - redundant_nil_coalescing
  - redundant_type_annotation
  # - required_deinit
  - required_enum_case
  - return_value_from_void_function
  - self_binding
  - shorthand_optional_binding
  - single_test_class
  - sorted_first_last
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - strong_iboutlet
  - switch_case_on_newline
  - test_case_accessibility
  - toggle_bool
  - trailing_closure
  - type_contents_order
  - unavailable_function
  - unneeded_parentheses_in_closure_argument
  - unowned_variable_capture
  - untyped_error_in_catch
  - vertical_parameter_alignment_on_call
  # - vertical_whitespace_between_cases
  - vertical_whitespace_closing_braces
  # - vertical_whitespace_opening_braces
  - weak_delegate
  - xct_specific_matcher
  - yoda_condition
 
custom_rules:
  # Empty line -----------------------------------------------------------------
  no_empty_line_after_func:
    name: "No empty line after init or func"
    regex: '(func|init|let\s|var\s)[^\n]*\{[^\n\{\}]*\n\n'
    message: "No empty line after init or func"
    severity: warning
 
  # Spacings -------------------------------------------------------------------
  empty_line_required:
    name: "Add empty line after class, struct, enum, extension or protocol"
    regex: '(class|struct|enum|extension|protocol)[^\n]*\{\n[^\n]*(class|struct|enum|extension|protocol|func|let|var|weak|private|internal|public|open|static|final|\/\/|init|case|@objc|@discardableResult)'
    message: "Add empty line after class, struct, enum, extension or protocol"
    severity: warning
    match_kinds:
      - argument
      - attribute.builtin
      - attribute.id
      - buildconfig.id
      - buildconfig.keyword
      - comment
      - comment.mark
      - comment.url
      - identifier
      - keyword
      - number
      - objectliteral
      - parameter
      - placeholder
      - string
      - string_interpolation_anchor
      - typeidentifier
 
  # Colors ---------------------------------------------------------------------
  forbidden_native_accentColor_modifier:
    name: "Native accentColor modifier"
    regex: '\.accentColor\('
    message: "[EnkiDesignSystem][AccentColor] Prefer use .enkiAccentColor() over .accentColor()"
    severity: warning
  forbidden_native_backgroundColor_modifier:
    name: "Native backgroundColor modifier"
    regex: '[^\(|BackgroundColorContext\.]\.background\(\.'
    message: "[EnkiDesignSystem][BackgroundColor] Prefer use .enkiBackgroundColor(color) over .background(color)"
    severity: warning
  forbidden_native_foregroundColor_modifier:
    name: "Native foregroundColor modifier"
    regex: '\.foregroundColor\('
    message: "[EnkiDesignSystem][ForegroundColor] Prefer use .enkiForegroundColor() over .foregroundColor()"
    severity: warning
  forbidden_native_shadow_modifier:
    name: "Native shadow modifier"
    regex: '\.shadow\('
    message: "[EnkiDesignSystem][Shadow] Prefer use .enkiShadow() over .shadow()"
    severity: warning
  forbidden_native_tint_modifier:
    name: "Native tint modifier"
    regex: '\.tint\('
    message: "[EnkiDesignSystem][Tint] Prefer use .enkiTint() over .tint()"
    severity: warning
   
  # Fonts ----------------------------------------------------------------------
  forbidden_native_text_modifier:
    name: "Native text modifier"
    regex: '\.font\(!(size)'
    message: "[EnkiDesignSystem][Font] Prefer use .enkiFont() over .font()"
    severity: warning
  forbidden_native_fontWeight_modifier:
    name: "Native fontWeight modifier"
    regex: '\.fontWeight\('
    message: "[EnkiDesignSystem][Font] Prefer use .enkiFont() over .fontWeight()"
    severity: warning
  forbidden_native_textCase_modifier:
    name: "Native textCase modifier"
    regex: '\.textCase\('
    message: "[EnkiDesignSystem][Font] Prefer use .enkiFont() over .textCase()"
    severity: warning
 
  # Padding --------------------------------------------------------------------
  forbidden_native_padding_modifier:
    name: "Native padding modifier"
    regex: '\.padding\('
    message: "[EnkiDesignSystem][Padding] Prefer use .enkiPadding() over .padding()"
    severity: warning
   
  # Radius ---------------------------------------------------------------------
  forbidden_native_radius_modifier:
    name: "Native radius modifier"
    regex: '\.cornerRadius\('
    message: "[EnkiDesignSystem][CornerRadius] Prefer use .enkiRadius() over .cornerRadius()"
    severity: warning
   
  # TabItem --------------------------------------------------------------------
  forbidden_native_tabItem_modifier:
    name: "Native tabItem modifier"
    regex: '\.tabItem'
    message: "[EnkiDesignSystem][TabItem] Prefer use .enkiTabItem over .tabItem"
    severity: warning
 
  # Vibration ------------------------------------------------------------------
  forbidden_native_vibration_generator:
    name: "Navigation vibration generator"
    regex: 'UINotificationFeedbackGenerator|UIImpactFeedbackGenerator|UISelectionFeedbackGenerator'
    message: "[EnkiDesignSystem][Vibration] Prefer use VibrationGenerator.generate(type:) over native vibration"
    severity: warning
 
  # Logger ---------------------------------------------------------------------
  forbidden_native_print:
    name: "Logger"
    regex: 'print\(|debugPrint\(|NSLog\('
    message: "[Logger] Prefer use Logger.log(message:) over print, debugPrint or NSLog methods."
    severity: warning